version: "3.7"
services:
  app:
    build:
      args:
        user: hugo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: full-stack
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - full-stack
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - full-stack
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secure_password
      MYSQL_DATABASE: challenge
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - database:/var/lib/mysql
    networks:
      - full-stack
    ports:
      - 33066:3306
networks:
  full-stack:
    driver: bridge

volumes:
  database:
